name: CI - DVC + Pytest + CML report

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      IRIS_CSV_PATH: data/iris.csv
      MODEL_PATH: model/model.joblib
      REPORT_PATH: report.md
      ACCURACY_THRESHOLD: "0.90"
      MIN_ACCURACY: "0.90"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup GCP auth (service account)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: DVC pull artifacts from GCS remote
        run: |
          # If the repo contains .dvc/config with remote pointing to gs://..., dvc pull will use gcloud auth
          dvc pull --verbose

      - name: Run pytest
        run: |
          echo "## ✅ Pytest Report" > report.md
          pytest -v --maxfail=1 --disable-warnings >> report.md

      - name: Run evaluation script (writes report.md)
        run: |
          python scripts/evaluate.py || true
          echo "-----" >> report.md
          cat report.md

      - name: Post evaluation report as PR comment (CML)
        uses: iterative/setup-cml@v1
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "# CML report" >> report.md
            cml comment create report.md
            
      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: iris-ci-report
          path: report.md

