name: CI - DVC + Pytest + CML report

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      IRIS_CSV_PATH: data/iris.csv
      MODEL_PATH: model/model.joblib
      REPORT_PATH: report.md
      ACCURACY_THRESHOLD: "0.90"
      MIN_ACCURACY: "0.90"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup GCP auth (service account)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Post evaluation report as PR comment (CML)
        uses: iterative/setup-cml@v2
      - name: DVC pull artifacts from GCS remote
        run: |
          # If the repo contains .dvc/config with remote pointing to gs://..., dvc pull will use gcloud auth
          dvc pull --verbose

      - name: Run pytest
        run: |
          echo "## ✅ Pytest Report" > test.txt
          pytest -v --maxfail=1 --disable-warnings >> test.txt

      - name: Run evaluation script
        run: |
          echo "-----" > evaluation.txt
          python scripts/evaluate.py >> evaluation.txt 2>&1 || true
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.CML_REPO_TOKEN }}
        run: |
          echo "# CML report" > report.md
          cat test.txt >> report.md
          cat evaluation.txt >> report.md
          cml comment create --publish report.md